/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./../src/components/Layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./../src/components/Layouts/BaseSide.vue')['default']
    DragTool: typeof import('./../src/components/DragTool.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Form: typeof import('./../src/components/Form/Form.vue')['default']
    GoBack: typeof import('./../src/components/demo/GoBack.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    Index: typeof import('./../src/components/demo/Index.vue')['default']
    IpcDemo: typeof import('./../src/components/demo/ipcDemo.vue')['default']
    Language: typeof import('./../src/components/Language.vue')['default']
    Login: typeof import('./../src/components/Login/Login.vue')['default']
    MockApiDemo: typeof import('./../src/components/demo/MockApiDemo.vue')['default']
    MockDemo: typeof import('./../src/components/demo/MockDemo.vue')['default']
    PiniaTest: typeof import('./../src/components/demo/PiniaTest.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SassDemo: typeof import('./../src/components/demo/SassDemo.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon.vue')['default']
    ThemeDemo: typeof import('./../src/components/demo/ThemeDemo.vue')['default']
    ThemeSwitch: typeof import('./../src/components/ThemeSwitch.vue')['default']
    WeiXinLogin: typeof import('./../src/components/demo/WeiXinLogin.vue')['default']
    WindowPositionDemo: typeof import('./../src/components/demo/WindowPositionDemo.vue')['default']
  }
}
